@startuml
title PIS

package PIS.Models
{
    class Project{
        +Id:int
        +Title:String
        +Budge:decimal
    }

    class ProjectManager
    {
        -_list:List<Project>
        --
        +ProjectManager()
        +GetAll():List<Project>
    }
}

package PIS.Controllers
{
    class ProjectController
    {
        + Index() : IActionResult
    }
}

ProjectManager - Project :  > "manages" 
hide empty members
@enduml