@startuml
title PIS

package PIS.Models
{
    class Project
    {
        +Id:int
        +Title:String
        +Budget:Decimal
    }

    class ProjectManager
    {
        -_list:List<Project>
    }
}

ProjectManager - Project : > "manages"

hide empty members
@enduml