@startuml
title PIS

package PIS.Models
{
    class Project
    {
        +Id:int
        +Title:String
        +Budget:Decimal
    }

    class ProjectManager
    {
        -_list:List<Project>
        
        +GetAll():List<Project>
        +Create(project:Project):Project
        +GetById(id:int):Project
        +Update(project:Project):bool
        +Delete(id:int):bool
    }
}

package PIS.Controllers 
{
    class ProjectManagerController{
        +Index():IActionResult
        +Details(id:int):IActionResult
        +Create():IActionResult
        +Create(project:Project):IActionResult
    }
}

class Controller{}

ProjectManager - Project : > "manages"
ProjectManagerController -up-|> Controller : "<<extends>>"
ProjectManagerController ..> ProjectManager : "uses"



hide empty members
@enduml
